theme: jekyll-theme-cayman
title: Manual til DDB CMS NEXT (forsøg)
description: Manualer til både indholdsredaktøren og lokal-administratoren der skal konfigurere websitet
github:
  is_project_page: false
